on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mercurial Clone
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        hg clone --ssh="ssh -o 'StrictHostKeyChecking no'" ssh://hg@codebasehq.com/digi-labs/cerulean/sonarview.hg ./sonarview
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts'
    - name: Build
      run: |
        cd ./sonarview
        npm i
        npx quasar build -m electron -T all -P always
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
