on:
  workflow_dispatch:
  push:
jobs:
  build:
    # note that we can't build for macOS from Linux
    runs-on: macos-latest
    steps:
    - name: Set up software
      if: runner.os == 'macOS'
      run:
        brew install mercurial
    - name: Mercurial Clone
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        hg clone --ssh="ssh -o 'StrictHostKeyChecking no'" ssh://hg@codebasehq.com/digi-labs/cerulean/sonarview.hg ./sonarview
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Build
      run: |
        cd ./sonarview
        npm ci
        # npm i --save-dev dmg-license # a dependency of electron-builder when building for macOS
        npx quasar build -m electron -T all -P always
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
